name: CI Workflow   # 워크플로우 이름 (GitHub Actions 탭에서 표시되는 이름)

on:                 # 워크플로우 실행 조건(트리거 이벤트) 정의
  push:             # pull_request 이벤트 발생 시 실행 -> 나중에 pull_request로 변경해야 함!!!!!!!!!!!!!
    branches: [ "sprint8" ]   # main 브랜치에 pull_request될 때만 실행

jobs:               # 실행할 작업(job)들을 정의
  build:            # "build"라는 이름의 job
    runs-on: ubuntu-latest   # 실행 환경: GitHub이 제공하는 Ubuntu 최신 버전 가상 머신

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ap-northeast-2

    steps:          # job 안에서 실행할 단계(step)들
      - uses: actions/checkout@v3   # 현재 리포지토리의 소스 코드를 체크아웃 (가져오기)

      - name: JDK 17 설정
        uses: actions/setup-java@v1   # Java 환경을 세팅하는 공식 액션
        with:
          java-version: '17'          # 설치할 Java 버전 (여기서는 JDK 17)

      - name: AWS CLI 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 환경 변수 테스트
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "DB_PASSWORD 값은 숨김 처리되어 로그에는 보이지 않습니다."

      - name: 빌드 및 테스트
        run: ./gradlew clean build    # Gradle 빌드 및 테스트 실행 (clean 후 build)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml # codecov가 시각화 할 수 있는 report 파일 의미, 프로젝트 빌드와 테스트 수행 시 gradle build 결과물 내에서 확인

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AWS 인증
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 버킷 목록 출력
        run: aws s3 ls

      - name: DB_PASSWORD 시크릿 확인
        run: |
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "시크릿 값이 없습니다."
            exit 1
          else
            echo "DB_PASSWORD 시크릿이 정상적으로 설정되었습니다."
          fi